apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:z1aqKlDP9JI6gW0=,iv:i/CVw/pUmRXtk0/pGEEyjALyO/i8gHBITalbcBsV1ow=,tag:A1svTRwwi0/q/D6HXw68Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dn4tp0j9vgf3v83dwmprj8xtuuvs9whnfyjn8pmxw2vxrncdwvnql2lu2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbDZhNmVzc3BzUjNkSVBP
            YU5aMXhPOUEva0EzempPUHU2OEFhOUxkSWlNCjc4UVBtRTltMWt1VWRidWg5RENu
            eHJOcGJ4NGF6K1RvRnhXZ1EwYjhDZEEKLS0tIHZnclJRelBzVmJWbE1hZTJUaHJY
            YVJtSmpyZW42YlhZZTdOSjNSa2hVamMKugyHavA3+G62ZkfE75KtBo8sCnLEIwWZ
            m8ZSf9RdNLDKxu1z2e5o3Nv2NwQGoY58dg3X3Ik9jdG9N8SY+1eYaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T11:07:21Z"
    mac: ENC[AES256_GCM,data:BsScvaQVrBiKv/VQ1CjpKNKP8ZfO+oEhVGorUchqdE/4SEmvQQUHtOf1c/7ANXAZruyY+INGvumIwooc53OyJBDvU85MofJkLUUp3GbUD/Nz+qFhFLn/46ftKDqfzpwUgnKT1KM0oD1IB7nT03+7TbhUkhymvOLk7BE6B50BL6E=,iv:fnuhxx3JoR8AgHFqKL3D5pjJlI9sCu1j0XZkuWQD5tk=,tag:HG8nU2ZsRQzkvA024RufsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
